package com.somnyralab.zombiedefense;

import android.content.*;import android.graphics.*;import android.view.*;import java.util.*;

/** Last Stand 2.0 - rebuilt controls, balance and arena. */
public final class GameView extends View {
 private enum Screen{MENU,GAME,UPGRADE,OVER} private final Paint p=new Paint(3),line=new Paint(3);private final Random rng=new Random();
 private final ArrayList<Enemy> enemies=new ArrayList<>();private final ArrayList<Shot> shots=new ArrayList<>();private final ArrayList<Spark> sparks=new ArrayList<>();private final ArrayList<Drop> drops=new ArrayList<>();
 private final SharedPreferences save;private Screen screen=Screen.MENU;private float W,H,S,px,py,mx,my,fx=1,fy,jx,jy,shake,red,muzzle,reload;private int pointer=-1,hp,maxHp,wave,kills,coins,best,ammo,clip,damage;private float speed,fireGap,shotSpeed;private long previous,lastFire,nextHit,waveStart;
 public GameView(Context c){super(c);setFocusable(true);setLayerType(View.LAYER_TYPE_HARDWARE,null);save=c.getSharedPreferences("last_stand_2",0);best=save.getInt("best",0);line.setStyle(Paint.Style.STROKE);line.setStrokeCap(Paint.Cap.ROUND);}
 @Override protected void onSizeChanged(int w,int h,int ow,int oh){W=w;H=h;S=Math.min(W/1280f,H/720f);jx=125*S;jy=H-125*S;px=W*.5f;py=H*.55f;}
 private void start(){hp=maxHp=120;wave=1;kills=coins=0;clip=ammo=24;damage=28;speed=300;fireGap=.24f;shotSpeed=900;px=W*.5f;py=H*.55f;enemies.clear();shots.clear();sparks.clear();drops.clear();lastFire=0;reload=0;spawnWave();screen=Screen.GAME;}
 private void spawnWave(){enemies.clear();shots.clear();ammo=clip;reload=0;int count=3+wave*2;for(int i=0;i<count;i++){double a=Math.PI*2*i/count+rng.nextFloat()*.35;float r=Math.max(W,H)*(.58f+rng.nextFloat()*.15f);int type=wave>=5&&i%7==0?2:(wave>=3&&i%5==0?1:0);enemies.add(new Enemy(px+(float)Math.cos(a)*r,py+(float)Math.sin(a)*r,type));}waveStart=System.currentTimeMillis();}
 @Override protected void onDraw(Canvas c){long now=System.currentTimeMillis();float dt=previous==0?0:Math.min(.032f,(now-previous)/1000f);previous=now;drawArena(c);if(screen==Screen.GAME)update(dt,now);if(shake>0&&screen==Screen.GAME){c.save();c.translate((rng.nextFloat()-.5f)*shake*S,(rng.nextFloat()-.5f)*shake*S);}if(screen!=Screen.MENU)drawActors(c);if(shake>0&&screen==Screen.GAME)c.restore();if(screen==Screen.MENU)drawMenu(c);else if(screen==Screen.GAME)drawHUD(c);else if(screen==Screen.UPGRADE)drawUpgrade(c);else drawOver(c);invalidate();}
 private void update(float dt,long now){shake=Math.max(0,shake-dt*45);red=Math.max(0,red-dt*2.2f);muzzle=Math.max(0,muzzle-dt*10);px+=mx*speed*dt;py+=my*speed*dt;px=lim(px,55*S,W-55*S);py=lim(py,105*S,H-55*S);
  Enemy target=null;float nearest=Float.MAX_VALUE;for(Enemy e:enemies){float d=d2(px,py,e.x,e.y);if(d<nearest){nearest=d;target=e;}}if(target!=null){float dx=target.x-px,dy=target.y-py,l=(float)Math.hypot(dx,dy);if(l>1){fx=dx/l;fy=dy/l;}}
  if(reload>0){reload-=dt;if(reload<=0)ammo=clip;}else if(target!=null&&(now-lastFire)/1000f>=fireGap){if(ammo>0){shots.add(new Shot(px+fx*35*S,py+fy*35*S,fx*shotSpeed,fy*shotSpeed));ammo--;lastFire=now;muzzle=1;shake=1.8f;}else reload=.85f;}
  for(int i=shots.size()-1;i>=0;i--){Shot b=shots.get(i);b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;boolean gone=b.life<=0;for(int j=enemies.size()-1;!gone&&j>=0;j--){Enemy e=enemies.get(j);float r=e.r+8*S;if(d2(b.x,b.y,e.x,e.y)<r*r){e.hp-=damage;e.flash=.11f;gone=true;burst(b.x,b.y,0xffffd45c,7);if(e.hp<=0){coins+=e.reward;kills++;drops.add(new Drop(e.x,e.y));burst(e.x,e.y,0xff9ece4d,16);enemies.remove(j);}}}if(gone)shots.remove(i);}
  for(Enemy e:enemies){e.flash=Math.max(0,e.flash-dt);float dx=px-e.x,dy=py-e.y,l=(float)Math.hypot(dx,dy);if(l>1){e.x+=dx/l*e.speed*dt;e.y+=dy/l*e.speed*dt;}if(l<e.r+28*S&&now>=nextHit){hp-=e.hit;nextHit=now+900;red=1;shake=8;burst(px,py,0xffff4d45,12);e.x-=dx/Math.max(1,l)*35*S;e.y-=dy/Math.max(1,l)*35*S;}}
  for(int i=drops.size()-1;i>=0;i--){Drop d=drops.get(i);d.life-=dt;if(d2(px,py,d.x,d.y)<1600*S*S){coins++;drops.remove(i);}else if(d.life<=0)drops.remove(i);}for(int i=sparks.size()-1;i>=0;i--){Spark q=sparks.get(i);q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;if(q.life<=0)sparks.remove(i);}
  if(hp<=0){best=Math.max(best,wave);save.edit().putInt("best",best).apply();screen=Screen.OVER;}else if(enemies.isEmpty()&&now-waveStart>700){coins+=5+wave;screen=Screen.UPGRADE;}}
 private void drawArena(Canvas c){c.drawColor(0xff0b1210);p.setColor(0xff101d18);float g=72*S;for(float x=0;x<W;x+=g)c.drawRect(x,0,x+S,H,p);for(float y=0;y<H;y+=g)c.drawRect(0,y,W,y+S,p);p.setColor(0xff17251e);for(int i=0;i<28;i++){float x=(i*211%1270)/1280f*W,y=(i*337%710)/720f*H;c.drawCircle(x,y,(5+i%5)*S,p);}line.setColor(0xff314837);line.setStrokeWidth(4*S);c.drawRoundRect(26*S,88*S,W-26*S,H-26*S,18*S,18*S,line);crate(c,W*.22f,H*.28f);crate(c,W*.78f,H*.72f);crate(c,W*.72f,H*.24f);}
 private void crate(Canvas c,float x,float y){p.setColor(0xff27352b);c.drawRoundRect(x-30*S,y-24*S,x+30*S,y+24*S,5*S,5*S,p);line.setColor(0xff465744);line.setStrokeWidth(3*S);c.drawLine(x-23*S,y-17*S,x+23*S,y+17*S,line);c.drawLine(x+23*S,y-17*S,x-23*S,y+17*S,line);}
 private void drawActors(Canvas c){for(Drop d:drops){p.setColor(0xffffd95b);c.drawCircle(d.x,d.y,7*S,p);}for(Shot b:shots){p.setColor(0xffffe17b);p.setStrokeWidth(5*S);c.drawLine(b.x-b.vx*.014f,b.y-b.vy*.014f,b.x,b.y,p);}for(Enemy e:enemies)enemy(c,e);for(Spark q:sparks){p.setColor(q.color);p.setAlpha((int)(255*q.life/.5f));c.drawCircle(q.x,q.y,3.5f*S,p);p.setAlpha(255);}hero(c);}
 private void hero(Canvas c){float a=(float)Math.toDegrees(Math.atan2(fy,fx));c.save();c.rotate(a,px,py);p.setColor(0xff17221d);c.drawCircle(px,py,29*S,p);p.setColor(0xff3b8064);c.drawCircle(px-5*S,py,23*S,p);p.setColor(0xffd9c8a0);c.drawCircle(px+6*S,py,13*S,p);p.setColor(0xff242925);c.drawRoundRect(px+4*S,py-6*S,px+47*S,py+6*S,4*S,4*S,p);if(muzzle>0){p.setColor(0xffffdf66);c.drawCircle(px+55*S,py,(6+8*muzzle)*S,p);}c.restore();bar(c,px-32*S,py-45*S,64*S,7*S,hp/(float)maxHp,0xff54d377);}
 private void enemy(Canvas c,Enemy e){p.setColor(0x55000000);c.drawOval(e.x-e.r,e.y+e.r*.45f,e.x+e.r,e.y+e.r*.9f,p);int col=e.type==2?0xffb65648:e.type==1?0xff61963d:0xff88b64e;p.setColor(e.flash>0?0xffffefa6:col);c.drawCircle(e.x,e.y,e.r,p);p.setColor(0xffdff071);c.drawCircle(e.x-e.r*.3f,e.y-e.r*.12f,4*S,p);c.drawCircle(e.x+e.r*.3f,e.y-e.r*.12f,4*S,p);if(e.hp<e.max)bar(c,e.x-e.r,e.y-e.r-10*S,e.r*2,5*S,e.hp/e.max,0xffe45a50);}
 private void drawHUD(Canvas c){panel(c,18*S,15*S,315*S,88*S,0xdd101b16);text(c,"WAVE "+wave,34*S,34*S,52*S,0xffffedc0,true,Paint.Align.LEFT);text(c,"KILLS  "+kills+"     COINS  "+coins,17*S,34*S,77*S,0xff9fb0a5,false,Paint.Align.LEFT);panel(c,W-230*S,17*S,W-18*S,83*S,0xdd101b16);text(c,reload>0?"RELOADING":ammo+" / "+clip,22*S,W-38*S,58*S,reload>0?0xffff8b55:0xffffd75c,true,Paint.Align.RIGHT);joystick(c);text(c,"AUTO FIRE",14*S,W-105*S,H-108*S,0xff7f9186,true,Paint.Align.CENTER);line.setColor(0x337f9186);line.setStrokeWidth(3*S);c.drawCircle(W-105*S,H-113*S,58*S,line);if(red>0){p.setColor(((int)(100*red)<<24)|0x00d32622);c.drawRect(0,0,W,H,p);}}
 private void joystick(Canvas c){p.setColor(0x332d7d60);c.drawCircle(jx,jy,72*S,p);line.setColor(0xaa77a38d);line.setStrokeWidth(4*S);c.drawCircle(jx,jy,66*S,line);p.setColor(pointer>=0?0xffc5d7cd:0xff73877b);c.drawCircle(jx+mx*47*S,jy+my*47*S,28*S,p);text(c,"MOVE",13*S,jx,jy+5*S,0xff16231c,true,Paint.Align.CENTER);}
 private void drawMenu(Canvas c){p.setShader(new LinearGradient(0,0,0,H,0x00101814,0xee050806,Shader.TileMode.CLAMP));c.drawRect(0,0,W,H,p);p.setShader(null);text(c,"LAST STAND",78*S,W/2,H*.3f,0xffffedcf,true,Paint.Align.CENTER);text(c,"ZOMBIE ARENA",25*S,W/2,H*.38f,0xffa8d452,true,Paint.Align.CENTER);button(c,W/2-180*S,H*.53f,W/2+180*S,H*.66f,"START SURVIVAL");text(c,"Best wave  "+best,19*S,W/2,H*.75f,0xff8d9c92,false,Paint.Align.CENTER);text(c,"Move with one thumb. Your weapon fires automatically.",17*S,W/2,H*.84f,0xff65756b,false,Paint.Align.CENTER);}
 private void drawUpgrade(Canvas c){p.setColor(0xee060a08);c.drawRect(0,0,W,H,p);text(c,"WAVE "+wave+" CLEARED",40*S,W/2,70*S,0xffffdb62,true,Paint.Align.CENTER);text(c,"CHOOSE AN UPGRADE",18*S,W/2,104*S,0xff91a096,false,Paint.Align.CENTER);float cw=270*S,g=20*S,l=W/2-(cw*1.5f+g),t=155*S;card(c,l,t,cw,"POWER","Damage +10",0);card(c,l+cw+g,t,cw,"FIRE RATE","Shoot 15% faster",1);card(c,l+(cw+g)*2,t,cw,"ARMOR","Heal 45 / Max HP +15",2);}
 private void drawOver(Canvas c){p.setColor(0xeb090706);c.drawRect(0,0,W,H,p);text(c,"YOU WERE OVERRUN",52*S,W/2,H*.3f,0xffff6258,true,Paint.Align.CENTER);text(c,"Wave "+wave+"  •  "+kills+" kills",25*S,W/2,H*.42f,0xffffe9cf,false,Paint.Align.CENTER);text(c,"Best wave  "+best,20*S,W/2,H*.49f,0xff98a49b,false,Paint.Align.CENTER);button(c,W/2-170*S,H*.58f,W/2+170*S,H*.71f,"TRY AGAIN");}
 private void card(Canvas c,float x,float y,float w,String title,String sub,int id){panel(c,x,y,x+w,y+300*S,0xff17231c);p.setColor(id==0?0xffffcd55:id==1?0xff65b8e8:0xff65d385);c.drawCircle(x+w/2,y+70*S,40*S,p);text(c,id==0?"PWR":id==1?"SPD":"HP",18*S,x+w/2,y+77*S,0xff101610,true,Paint.Align.CENTER);text(c,title,23*S,x+w/2,y+150*S,0xffffeed2,true,Paint.Align.CENTER);text(c,sub,17*S,x+w/2,y+188*S,0xff9aaba0,false,Paint.Align.CENTER);panel(c,x+28*S,y+225*S,x+w-28*S,y+270*S,0xff304638);text(c,"SELECT",16*S,x+w/2,y+254*S,0xffe7f2e9,true,Paint.Align.CENTER);}
 @Override public boolean onTouchEvent(MotionEvent e){int a=e.getActionMasked();float x=e.getX(),y=e.getY();if(a==MotionEvent.ACTION_DOWN&&screen==Screen.MENU){start();return true;}if(a==MotionEvent.ACTION_DOWN&&screen==Screen.OVER){start();return true;}if(a==MotionEvent.ACTION_DOWN&&screen==Screen.UPGRADE){choose(x,y);return true;}if(screen!=Screen.GAME)return true;if(a==MotionEvent.ACTION_DOWN&&x<W*.48f){pointer=e.getPointerId(0);move(x,y);}else if(a==MotionEvent.ACTION_MOVE&&pointer>=0){int i=e.findPointerIndex(pointer);if(i>=0)move(e.getX(i),e.getY(i));}else if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_CANCEL){pointer=-1;mx=my=0;}return true;}
 private void move(float x,float y){float dx=x-jx,dy=y-jy,l=(float)Math.hypot(dx,dy);if(l<9*S){mx=my=0;}else{mx=dx/l;my=dy/l;}}
 private void choose(float x,float y){float cw=270*S,g=20*S,l=W/2-(cw*1.5f+g);int pick=(int)((x-l)/(cw+g));if(pick<0||pick>2)return;if(pick==0)damage+=10;else if(pick==1)fireGap=Math.max(.09f,fireGap*.85f);else{maxHp+=15;hp=Math.min(maxHp,hp+45);}wave++;spawnWave();screen=Screen.GAME;}
 private void burst(float x,float y,int col,int n){for(int i=0;i<n;i++){double a=rng.nextDouble()*Math.PI*2;float v=40+rng.nextFloat()*150;sparks.add(new Spark(x,y,(float)Math.cos(a)*v,(float)Math.sin(a)*v,col));}}
 private void bar(Canvas c,float x,float y,float w,float h,float v,int col){p.setColor(0xff263229);c.drawRoundRect(x,y,x+w,y+h,h/2,h/2,p);p.setColor(col);c.drawRoundRect(x,y,x+w*lim(v,0,1),y+h,h/2,h/2,p);}private void panel(Canvas c,float l,float t,float r,float b,int col){p.setColor(col);c.drawRoundRect(l,t,r,b,16*S,16*S,p);}private void button(Canvas c,float l,float t,float r,float b,String s){panel(c,l,t,r,b,0xffffcb52);text(c,s,22*S,(l+r)/2,(t+b)/2+8*S,0xff121710,true,Paint.Align.CENTER);}private void text(Canvas c,String s,float z,float x,float y,int col,boolean bold,Paint.Align a){p.setShader(null);p.setColor(col);p.setTextSize(z);p.setTextAlign(a);p.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);c.drawText(s,x,y,p);}private float lim(float v,float a,float b){return Math.max(a,Math.min(b,v));}private float d2(float x,float y,float a,float b){float dx=x-a,dy=y-b;return dx*dx+dy*dy;}
 private final class Enemy{float x,y,hp,max,speed,r,flash;int type,hit,reward;Enemy(float x,float y,int type){this.x=x;this.y=y;this.type=type;if(type==2){max=hp=180+wave*16;speed=42+wave*1.5f;r=37*S;hit=12;reward=8;}else if(type==1){max=hp=48+wave*5;speed=105+wave*2;r=22*S;hit=7;reward=4;}else{max=hp=70+wave*7;speed=58+wave*2;r=28*S;hit=8;reward=3;}}}private static final class Shot{float x,y,vx,vy,life=1.4f;Shot(float x,float y,float vx,float vy){this.x=x;this.y=y;this.vx=vx;this.vy=vy;}}private static final class Spark{float x,y,vx,vy,life=.5f;int color;Spark(float x,float y,float vx,float vy,int c){this.x=x;this.y=y;this.vx=vx;this.vy=vy;color=c;}}private static final class Drop{float x,y,life=6;Drop(float x,float y){this.x=x;this.y=y;}}
}
