package com.somnyralab.zombiedefense;

import android.content.*;import android.graphics.*;import android.view.*;import java.util.*;

/** Last Stand 2.0 - rebuilt controls, balance and arena. */
public final class GameView extends View {
 private enum Screen{SPLASH,MENU,GAME,UPGRADE,OVER} private final Paint p=new Paint(3),line=new Paint(3);private final Random rng=new Random();
 private final ArrayList<Enemy> enemies=new ArrayList<>();private final ArrayList<Shot> shots=new ArrayList<>();private final ArrayList<Spark> sparks=new ArrayList<>();private final ArrayList<Drop> drops=new ArrayList<>();
 private final SharedPreferences save;private Screen screen=Screen.SPLASH;private float W,H,S,px,py,mx,my,ax=1,ay,fx=1,fy,jx,jy,ajx,ajy,shake,red,muzzle,reload,dashCd,dashTime,comboTime;private int movePointer=-1,aimPointer=-1,hp,maxHp,wave,kills,coins,best,ammo,clip,damage,score,combo,waveTotal;private float speed,fireGap,shotSpeed;private long previous,lastFire,nextHit,waveStart,lastMoveTap,splashStart;
 public GameView(Context c){super(c);setFocusable(true);setLayerType(View.LAYER_TYPE_HARDWARE,null);save=c.getSharedPreferences("last_stand_2",0);best=save.getInt("best",0);splashStart=System.currentTimeMillis();line.setStyle(Paint.Style.STROKE);line.setStrokeCap(Paint.Cap.ROUND);}
 @Override protected void onSizeChanged(int w,int h,int ow,int oh){W=w;H=h;S=Math.min(W/1280f,H/720f);jx=125*S;jy=H-125*S;ajx=W-125*S;ajy=H-125*S;px=W*.5f;py=H*.55f;}
 private void start(){hp=maxHp=100;wave=1;kills=coins=score=combo=0;clip=ammo=16;damage=24;speed=285;fireGap=.19f;shotSpeed=920;px=W*.5f;py=H*.55f;enemies.clear();shots.clear();sparks.clear();drops.clear();lastFire=0;reload=0;dashCd=0;spawnWave();screen=Screen.GAME;}
 private void spawnWave(){enemies.clear();shots.clear();ammo=clip;reload=0;int count=4+wave*2;waveTotal=count;for(int i=0;i<count;i++){double a=Math.PI*2*i/count+rng.nextFloat()*.3;float r=Math.max(W,H)*(.6f+rng.nextFloat()*.16f);int type=(wave%5==0&&i==0)?2:(wave>=2&&i%4==0?1:0);enemies.add(new Enemy(px+(float)Math.cos(a)*r,py+(float)Math.sin(a)*r,type));}waveStart=System.currentTimeMillis();}
 @Override protected void onDraw(Canvas c){long now=System.currentTimeMillis();float dt=previous==0?0:Math.min(.032f,(now-previous)/1000f);previous=now;if(screen==Screen.SPLASH){drawSplash(c,now);invalidate();return;}drawArena(c);if(screen==Screen.GAME)update(dt,now);if(shake>0&&screen==Screen.GAME){c.save();c.translate((rng.nextFloat()-.5f)*shake*S,(rng.nextFloat()-.5f)*shake*S);}if(screen!=Screen.MENU)drawActors(c);if(shake>0&&screen==Screen.GAME)c.restore();if(screen==Screen.MENU)drawMenu(c);else if(screen==Screen.GAME)drawHUD(c);else if(screen==Screen.UPGRADE)drawUpgrade(c);else drawOver(c);invalidate();}
 private void update(float dt,long now){shake=Math.max(0,shake-dt*45);red=Math.max(0,red-dt*2.2f);muzzle=Math.max(0,muzzle-dt*10);dashCd=Math.max(0,dashCd-dt);dashTime=Math.max(0,dashTime-dt);comboTime-=dt;if(comboTime<=0)combo=0;float boost=dashTime>0?3.2f:1;px+=mx*speed*boost*dt;py+=my*speed*boost*dt;px=lim(px,55*S,W-55*S);py=lim(py,105*S,H-55*S);if(aimPointer>=0){fx=ax;fy=ay;}
  if(reload>0){reload-=dt;if(reload<=0)ammo=clip;}else if(aimPointer>=0&&(now-lastFire)/1000f>=fireGap){if(ammo>0){shots.add(new Shot(px+fx*35*S,py+fy*35*S,fx*shotSpeed,fy*shotSpeed));ammo--;lastFire=now;muzzle=1;shake=2.2f;}else reload=1.15f;}
  for(int i=shots.size()-1;i>=0;i--){Shot b=shots.get(i);b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;boolean gone=b.life<=0;for(int j=enemies.size()-1;!gone&&j>=0;j--){Enemy e=enemies.get(j);float r=e.r+8*S;if(d2(b.x,b.y,e.x,e.y)<r*r){boolean critical=rng.nextFloat()<.14f;int dealt=critical?damage*2:damage;e.hp-=dealt;e.flash=.11f;gone=true;burst(b.x,b.y,critical?0xffffef78:0xffffd45c,critical?13:7);if(e.hp<=0){combo=Math.min(9,combo+1);comboTime=2.2f;score+=100*combo;coins+=e.reward;kills++;drops.add(new Drop(e.x,e.y,rng.nextFloat()<.14f));burst(e.x,e.y,0xff9ece4d,16);enemies.remove(j);}}}if(gone)shots.remove(i);}
  for(Enemy e:enemies){e.flash=Math.max(0,e.flash-dt);float dx=px-e.x,dy=py-e.y,l=(float)Math.hypot(dx,dy);if(l>1){e.x+=dx/l*e.speed*dt;e.y+=dy/l*e.speed*dt;}if(l<e.r+28*S&&now>=nextHit&&dashTime<=0){hp-=e.hit;nextHit=now+620;red=1;shake=10;burst(px,py,0xffff4d45,12);e.x-=dx/Math.max(1,l)*35*S;e.y-=dy/Math.max(1,l)*35*S;}}
  for(int i=drops.size()-1;i>=0;i--){Drop d=drops.get(i);d.life-=dt;if(d2(px,py,d.x,d.y)<1900*S*S){if(d.heal)hp=Math.min(maxHp,hp+22);else coins++;drops.remove(i);}else if(d.life<=0)drops.remove(i);}for(int i=sparks.size()-1;i>=0;i--){Spark q=sparks.get(i);q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;if(q.life<=0)sparks.remove(i);}
  if(hp<=0){best=Math.max(best,wave);save.edit().putInt("best",best).apply();screen=Screen.OVER;}else if(enemies.isEmpty()&&now-waveStart>700){coins+=5+wave;screen=Screen.UPGRADE;}}
 private void drawArena(Canvas c){c.drawColor(0xff080d0b);p.setShader(new RadialGradient(W*.5f,H*.48f,Math.max(W,H)*.58f,0xff233329,0xff070b09,Shader.TileMode.CLAMP));c.drawRect(0,0,W,H,p);p.setShader(null);p.setColor(0x331e3328);float g=72*S;for(float x=0;x<W;x+=g)c.drawRect(x,0,x+S,H,p);for(float y=0;y<H;y+=g)c.drawRect(0,y,W,y+S,p);p.setColor(0xff1b2922);for(int i=0;i<32;i++){float x=(i*211%1270)/1280f*W,y=(i*337%710)/720f*H;c.drawCircle(x,y,(4+i%6)*S,p);}line.setColor(0xff4a5e4d);line.setStrokeWidth(5*S);c.drawRoundRect(25*S,87*S,W-25*S,H-25*S,20*S,20*S,line);line.setColor(0x55e2a839);line.setStrokeWidth(2*S);c.drawRoundRect(34*S,96*S,W-34*S,H-34*S,16*S,16*S,line);crate(c,W*.22f,H*.28f);crate(c,W*.78f,H*.72f);crate(c,W*.72f,H*.24f);barrel(c,W*.34f,H*.72f);barrel(c,W*.63f,H*.35f);p.setShader(new LinearGradient(0,0,W,0,0x00ffb533,0x22ffb533,Shader.TileMode.MIRROR));c.drawRect(0,92*S,W,98*S,p);p.setShader(null);}
 private void crate(Canvas c,float x,float y){p.setColor(0x66000000);c.drawOval(x-35*S,y+17*S,x+35*S,y+32*S,p);p.setColor(0xff3b3526);c.drawRoundRect(x-31*S,y-25*S,x+31*S,y+25*S,5*S,5*S,p);line.setColor(0xff80693c);line.setStrokeWidth(3*S);c.drawLine(x-23*S,y-17*S,x+23*S,y+17*S,line);c.drawLine(x+23*S,y-17*S,x-23*S,y+17*S,line);}
 private void barrel(Canvas c,float x,float y){p.setColor(0x66000000);c.drawOval(x-24*S,y+14*S,x+24*S,y+26*S,p);p.setColor(0xff6d2d24);c.drawRoundRect(x-19*S,y-24*S,x+19*S,y+24*S,8*S,8*S,p);p.setColor(0xffffa53c);c.drawRect(x-19*S,y-3*S,x+19*S,y+4*S,p);line.setColor(0xffad5541);line.setStrokeWidth(2*S);c.drawOval(x-19*S,y-25*S,x+19*S,y-15*S,line);}
 private void drawActors(Canvas c){for(Drop d:drops){p.setColor(d.heal?0xff59e38a:0xffffd95b);c.drawCircle(d.x,d.y,d.heal?10*S:7*S,p);if(d.heal){p.setColor(0xffffffff);p.setStrokeWidth(3*S);c.drawLine(d.x-5*S,d.y,d.x+5*S,d.y,p);c.drawLine(d.x,d.y-5*S,d.x,d.y+5*S,p);}}for(Shot b:shots){p.setColor(0xffffe17b);p.setStrokeWidth(5*S);c.drawLine(b.x-b.vx*.014f,b.y-b.vy*.014f,b.x,b.y,p);}for(Enemy e:enemies)enemy(c,e);for(Spark q:sparks){p.setColor(q.color);p.setAlpha((int)(255*q.life/.5f));c.drawCircle(q.x,q.y,3.5f*S,p);p.setAlpha(255);}hero(c);}
 private void hero(Canvas c){float a=(float)Math.toDegrees(Math.atan2(fy,fx));p.setShader(new RadialGradient(px,py,48*S,0x443ee08e,0x003ee08e,Shader.TileMode.CLAMP));c.drawCircle(px,py,48*S,p);p.setShader(null);c.save();c.rotate(a,px,py);p.setColor(0xff101713);c.drawOval(px-25*S,py+17*S,px+20*S,py+31*S,p);p.setColor(0xff20382d);c.drawCircle(px-8*S,py,28*S,p);p.setColor(0xff3f8c69);c.drawCircle(px-3*S,py,22*S,p);p.setColor(0xffcdbb91);c.drawCircle(px+8*S,py,13*S,p);p.setColor(0xff1c2420);c.drawRoundRect(px+2*S,py-8*S,px+49*S,py+8*S,5*S,5*S,p);p.setColor(0xff65736b);c.drawRect(px+10*S,py-6*S,px+38*S,py-3*S,p);if(muzzle>0){p.setColor(0xffffdf66);c.drawCircle(px+56*S,py,(7+9*muzzle)*S,p);}c.restore();bar(c,px-34*S,py-48*S,68*S,7*S,hp/(float)maxHp,0xff54d377);}
 private void enemy(Canvas c,Enemy e){p.setColor(0x66000000);c.drawOval(e.x-e.r,e.y+e.r*.5f,e.x+e.r,e.y+e.r*.95f,p);int col=e.type==2?0xff9e493f:e.type==1?0xff527f38:0xff789e49;p.setColor(e.flash>0?0xffffefa6:col);c.drawOval(e.x-e.r*.72f,e.y-e.r*.25f,e.x+e.r*.72f,e.y+e.r*.85f,p);p.setStrokeWidth((e.type==2?9:6)*S);p.setColor(e.flash>0?0xffffefa6:col);c.drawLine(e.x-e.r*.55f,e.y,e.x-e.r*1.05f,e.y+e.r*.38f,p);c.drawLine(e.x+e.r*.55f,e.y,e.x+e.r*1.05f,e.y+e.r*.38f,p);p.setColor(e.flash>0?0xffffefa6:(e.type==2?0xffb86550:0xff91b45c));c.drawCircle(e.x,e.y-e.r*.38f,e.r*.62f,p);p.setColor(0xffffdf5a);c.drawCircle(e.x-e.r*.23f,e.y-e.r*.48f,3.5f*S,p);c.drawCircle(e.x+e.r*.23f,e.y-e.r*.48f,3.5f*S,p);line.setColor(0xff263020);line.setStrokeWidth(2*S);c.drawLine(e.x-e.r*.25f,e.y-e.r*.18f,e.x+e.r*.26f,e.y-e.r*.2f,line);if(e.hp<e.max)bar(c,e.x-e.r,e.y-e.r-13*S,e.r*2,5*S,e.hp/e.max,0xffe45a50);}
 private void drawHUD(Canvas c){panel(c,18*S,15*S,340*S,92*S,0xdd101b16);text(c,"WAVE "+wave+"  •  "+enemies.size()+" LEFT",30*S,34*S,48*S,0xffffedc0,true,Paint.Align.LEFT);text(c,"SCORE "+score+"     COINS "+coins,16*S,34*S,76*S,0xff9fb0a5,false,Paint.Align.LEFT);panel(c,W-230*S,17*S,W-18*S,83*S,0xdd101b16);text(c,reload>0?"RELOADING":ammo+" / "+clip,22*S,W-38*S,58*S,reload>0?0xffff8b55:0xffffd75c,true,Paint.Align.RIGHT);if(combo>1)text(c,"x"+combo+" COMBO",24*S,W/2,48*S,0xffffd65d,true,Paint.Align.CENTER);joysticks(c);float dcx=W/2,dcy=H-88*S;p.setColor(dashCd<=0?0xffd9b64e:0xff38443c);c.drawCircle(dcx,dcy,48*S,p);text(c,dashCd<=0?"DASH":String.format(Locale.US,"%.1f",dashCd),13*S,dcx,dcy+5*S,dashCd<=0?0xff16170f:0xff94a096,true,Paint.Align.CENTER);if(hp<30){line.setColor(0x99ff453d);line.setStrokeWidth((4+(float)Math.sin(System.currentTimeMillis()*.01)*2)*S);c.drawRoundRect(8*S,8*S,W-8*S,H-8*S,20*S,20*S,line);}if(red>0){p.setColor(((int)(100*red)<<24)|0x00d32622);c.drawRect(0,0,W,H,p);}}
 private void joysticks(Canvas c){p.setColor(0x332d7d60);c.drawCircle(jx,jy,72*S,p);c.drawCircle(ajx,ajy,72*S,p);line.setColor(0xaa77a38d);line.setStrokeWidth(4*S);c.drawCircle(jx,jy,66*S,line);c.drawCircle(ajx,ajy,66*S,line);p.setColor(movePointer>=0?0xffc5d7cd:0xff73877b);c.drawCircle(jx+mx*47*S,jy+my*47*S,28*S,p);p.setColor(aimPointer>=0?0xffffd765:0xff73877b);c.drawCircle(ajx+ax*47*S,ajy+ay*47*S,28*S,p);text(c,"MOVE",13*S,jx,jy+5*S,0xff16231c,true,Paint.Align.CENTER);text(c,"AIM + FIRE",12*S,ajx,ajy+5*S,0xff16231c,true,Paint.Align.CENTER);}
 private void drawSplash(Canvas c,long now){c.drawColor(0xff050806);float elapsed=(now-splashStart)/1000f,alpha=Math.min(1,elapsed*2.4f);if(elapsed>1.45f)alpha=Math.max(0,1-(elapsed-1.45f)*1.8f);int gold=((int)(255*alpha)<<24)|0x00e7b847;text(c,"ACAR",78*S,W/2,H*.48f,gold,true,Paint.Align.CENTER);text(c,"GAME",32*S,W/2,H*.57f,gold,true,Paint.Align.CENTER);line.setColor(((int)(160*alpha)<<24)|0x00e7b847);line.setStrokeWidth(2*S);c.drawLine(W*.36f,H*.62f,W*.64f,H*.62f,line);if(elapsed>2.1f)screen=Screen.MENU;}
 private void drawMenu(Canvas c){p.setShader(new LinearGradient(0,0,0,H,0x00101814,0xee050806,Shader.TileMode.CLAMP));c.drawRect(0,0,W,H,p);p.setShader(null);text(c,"ACAR GAME",17*S,W/2,H*.13f,0xffffb747,true,Paint.Align.CENTER);text(c,"LAST STAND",76*S,W/2,H*.3f,0xffffedcf,true,Paint.Align.CENTER);text(c,"ZOMBIE ARENA",25*S,W/2,H*.38f,0xffffb747,true,Paint.Align.CENTER);button(c,W/2-180*S,H*.52f,W/2+180*S,H*.65f,"START SURVIVAL");text(c,"Best wave  "+best,19*S,W/2,H*.74f,0xffa2aea7,false,Paint.Align.CENTER);text(c,"Move left • Aim and fire right • Dash to escape",17*S,W/2,H*.83f,0xff718078,false,Paint.Align.CENTER);}
 private void drawUpgrade(Canvas c){p.setColor(0xee060a08);c.drawRect(0,0,W,H,p);text(c,"WAVE "+wave+" CLEARED",40*S,W/2,70*S,0xffffdb62,true,Paint.Align.CENTER);text(c,"CHOOSE AN UPGRADE",18*S,W/2,104*S,0xff91a096,false,Paint.Align.CENTER);float cw=270*S,g=20*S,l=W/2-(cw*1.5f+g),t=155*S;card(c,l,t,cw,"POWER","Damage +10",0);card(c,l+cw+g,t,cw,"FIRE RATE","Shoot 15% faster",1);card(c,l+(cw+g)*2,t,cw,"ARMOR","Heal 45 / Max HP +15",2);}
 private void drawOver(Canvas c){p.setColor(0xeb090706);c.drawRect(0,0,W,H,p);text(c,"YOU WERE OVERRUN",52*S,W/2,H*.27f,0xffff6258,true,Paint.Align.CENTER);text(c,"SCORE  "+score,30*S,W/2,H*.39f,0xffffd65d,true,Paint.Align.CENTER);text(c,"Wave "+wave+"  •  "+kills+" kills",23*S,W/2,H*.47f,0xffffe9cf,false,Paint.Align.CENTER);text(c,"Best wave  "+best,19*S,W/2,H*.53f,0xff98a49b,false,Paint.Align.CENTER);button(c,W/2-170*S,H*.61f,W/2+170*S,H*.74f,"TRY AGAIN");}
 private void card(Canvas c,float x,float y,float w,String title,String sub,int id){panel(c,x,y,x+w,y+300*S,0xff17231c);p.setColor(id==0?0xffffcd55:id==1?0xff65b8e8:0xff65d385);c.drawCircle(x+w/2,y+70*S,40*S,p);text(c,id==0?"PWR":id==1?"SPD":"HP",18*S,x+w/2,y+77*S,0xff101610,true,Paint.Align.CENTER);text(c,title,23*S,x+w/2,y+150*S,0xffffeed2,true,Paint.Align.CENTER);text(c,sub,17*S,x+w/2,y+188*S,0xff9aaba0,false,Paint.Align.CENTER);panel(c,x+28*S,y+225*S,x+w-28*S,y+270*S,0xff304638);text(c,"SELECT",16*S,x+w/2,y+254*S,0xffe7f2e9,true,Paint.Align.CENTER);}
 @Override public boolean onTouchEvent(MotionEvent e){int a=e.getActionMasked(),idx=e.getActionIndex(),id=e.getPointerId(idx);float x=e.getX(idx),y=e.getY(idx);if(a==MotionEvent.ACTION_DOWN&&screen==Screen.MENU){start();return true;}if(a==MotionEvent.ACTION_DOWN&&screen==Screen.OVER){start();return true;}if(a==MotionEvent.ACTION_DOWN&&screen==Screen.UPGRADE){choose(x,y);return true;}if(screen!=Screen.GAME)return true;
  if(a==MotionEvent.ACTION_DOWN||a==MotionEvent.ACTION_POINTER_DOWN){long now=System.currentTimeMillis();if(d2(x,y,W/2,H-88*S)<3600*S*S&&dashCd<=0){triggerDash();}else if(x<W*.48f&&movePointer<0){if(now-lastMoveTap<300&&dashCd<=0)triggerDash();lastMoveTap=now;movePointer=id;move(x,y);}else if(x>W*.52f&&aimPointer<0){aimPointer=id;aim(x,y);}}
  else if(a==MotionEvent.ACTION_MOVE){for(int i=0;i<e.getPointerCount();i++){int pid=e.getPointerId(i);if(pid==movePointer)move(e.getX(i),e.getY(i));if(pid==aimPointer)aim(e.getX(i),e.getY(i));}}
  else if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_POINTER_UP||a==MotionEvent.ACTION_CANCEL){if(id==movePointer){movePointer=-1;mx=my=0;}if(id==aimPointer)aimPointer=-1;}return true;}
 private void move(float x,float y){float dx=x-jx,dy=y-jy,l=(float)Math.hypot(dx,dy);if(l<9*S){mx=my=0;}else{mx=dx/l;my=dy/l;}}
 private void aim(float x,float y){float dx=x-ajx,dy=y-ajy,l=(float)Math.hypot(dx,dy);if(l>9*S){ax=dx/l;ay=dy/l;}}
 private void triggerDash(){dashTime=.22f;dashCd=3.0f;nextHit=System.currentTimeMillis()+350;shake=5;burst(px,py,0xff7de2bf,12);}
 private void choose(float x,float y){float cw=270*S,g=20*S,l=W/2-(cw*1.5f+g);int pick=(int)((x-l)/(cw+g));if(pick<0||pick>2)return;if(pick==0)damage+=10;else if(pick==1)fireGap=Math.max(.09f,fireGap*.85f);else{maxHp+=15;hp=Math.min(maxHp,hp+45);}wave++;spawnWave();screen=Screen.GAME;}
 private void burst(float x,float y,int col,int n){for(int i=0;i<n;i++){double a=rng.nextDouble()*Math.PI*2;float v=40+rng.nextFloat()*150;sparks.add(new Spark(x,y,(float)Math.cos(a)*v,(float)Math.sin(a)*v,col));}}
 private void bar(Canvas c,float x,float y,float w,float h,float v,int col){p.setColor(0xff263229);c.drawRoundRect(x,y,x+w,y+h,h/2,h/2,p);p.setColor(col);c.drawRoundRect(x,y,x+w*lim(v,0,1),y+h,h/2,h/2,p);}private void panel(Canvas c,float l,float t,float r,float b,int col){p.setColor(col);c.drawRoundRect(l,t,r,b,16*S,16*S,p);}private void button(Canvas c,float l,float t,float r,float b,String s){panel(c,l,t,r,b,0xffffcb52);text(c,s,22*S,(l+r)/2,(t+b)/2+8*S,0xff121710,true,Paint.Align.CENTER);}private void text(Canvas c,String s,float z,float x,float y,int col,boolean bold,Paint.Align a){p.setShader(null);p.setColor(col);p.setTextSize(z);p.setTextAlign(a);p.setTypeface(bold?Typeface.DEFAULT_BOLD:Typeface.DEFAULT);c.drawText(s,x,y,p);}private float lim(float v,float a,float b){return Math.max(a,Math.min(b,v));}private float d2(float x,float y,float a,float b){float dx=x-a,dy=y-b;return dx*dx+dy*dy;}
 private final class Enemy{float x,y,hp,max,speed,r,flash;int type,hit,reward;Enemy(float x,float y,int type){this.x=x;this.y=y;this.type=type;if(type==2){max=hp=300+wave*24;speed=55+wave*2;r=42*S;hit=18;reward=15;}else if(type==1){max=hp=55+wave*7;speed=128+wave*3;r=22*S;hit=9;reward=4;}else{max=hp=78+wave*10;speed=70+wave*3;r=28*S;hit=10;reward=3;}}}private static final class Shot{float x,y,vx,vy,life=1.4f;Shot(float x,float y,float vx,float vy){this.x=x;this.y=y;this.vx=vx;this.vy=vy;}}private static final class Spark{float x,y,vx,vy,life=.5f;int color;Spark(float x,float y,float vx,float vy,int c){this.x=x;this.y=y;this.vx=vx;this.vy=vy;color=c;}}private static final class Drop{float x,y,life=6;boolean heal;Drop(float x,float y,boolean heal){this.x=x;this.y=y;this.heal=heal;}}
}
